{% set name = "git-bash" %}
{% set version = "2.24.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True  # [not win64]
  number: 0

requirements:
  run:
    - conda-forge::git ={{ version }}

test:
  commands:
    - bash --version
    - git --version
    # - |
    #   bash -c "if [[ $(echo hello | cp /dev/stdin /dev/stdout) != 'hello' ]]; then exit 1; fi"

about:
  home: https://anaconda.org/conda-forge/git
  license: GPL-2 AND LGPL-2.1 AND GPL-3
  license_family: OTHER
  license_file: LICENSE
  summary: "A dummy package that depends on conda-forge::git"

extra:
  recipe-maintainers:
    - kiwi0fruit
